# Generated by Django 4.2.7 on 2023-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('idcareer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('shortname', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=10)),
                ('state', models.BooleanField()),
            ],
        ),
    ]
